In [1]:
a=6 

In [2]:
a=8

In [3]:
import numpy as np

In [4]:
it = [3,5,7,11]

In [5]:
n = np.array(it)

In [6]:
n

array([ 3,  5,  7, 11])

In [7]:
type(n)

numpy.ndarray

In [9]:
np.array({2,5,7})

array({2, 5, 7}, dtype=object)

In [16]:
twod = np.array([[1,2],[4,5]])
twod

array([[1, 2],
       [4, 5]])

In [15]:
unicode = np.array([2,5,7,"11"])
unicode

array(['2', '5', '7', '11'], dtype='<U21')

In [18]:
list(range(7,15,2))

[7, 9, 11, 13]

In [19]:
np.arange(7,15,2)

array([ 7,  9, 11, 13])

In [21]:
np.arange(49).reshape(7,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [23]:
arr1 = np.arange(100)

In [24]:
arr2 = arr1.reshape(10,10)

In [25]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
arr1[0] = 1000

In [29]:
arr2

array([[1000,    1,    2,    3,    4,    5,    6,    7,    8,    9],
       [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24,   25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34,   35,   36,   37,   38,   39],
       [  40,   41,   42,   43,   44,   45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54,   55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64,   65,   66,   67,   68,   69],
       [  70,   71,   72,   73,   74,   75,   76,   77,   78,   79],
       [  80,   81,   82,   83,   84,   85,   86,   87,   88,   89],
       [  90,   91,   92,   93,   94,   95,   96,   97,   98,   99]])